-- ============================================================================
-- Supabase Schema for Starter App
-- Run this script in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================================

-- 1. Create items table
CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Performance Index on user_id
CREATE INDEX IF NOT EXISTS items_user_id_idx ON public.items(user_id);

-- 3. Enable Row-Level Security (RLS)
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies: Users can only see and manipulate their own items
DROP POLICY IF EXISTS "Users can view their own items" ON public.items;
CREATE POLICY "Users can view their own items" 
    ON public.items FOR SELECT 
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own items" ON public.items;
CREATE POLICY "Users can insert their own items" 
    ON public.items FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own items" ON public.items;
CREATE POLICY "Users can update their own items" 
    ON public.items FOR UPDATE 
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own items" ON public.items;
CREATE POLICY "Users can delete their own items" 
    ON public.items FOR DELETE 
    USING (auth.uid() = user_id);
