-- ============================================================================
-- Supabase Schema for Starter App
-- Run this script in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================================

-- 1. Create items table with TEXT user_id (supports both Supabase Auth UUIDs & demo users)
CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- In case table already exists with UUID type:
ALTER TABLE public.items DROP CONSTRAINT IF EXISTS items_user_id_fkey;
ALTER TABLE public.items ALTER COLUMN user_id TYPE TEXT;

-- 2. Performance Index on user_id
CREATE INDEX IF NOT EXISTS items_user_id_idx ON public.items(user_id);

-- 3. Enable Row-Level Security (RLS)
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies: Allow read/write for all operations (API server manages authorization)
DROP POLICY IF EXISTS "Allow all for authenticated/service" ON public.items;
CREATE POLICY "Allow all for authenticated/service"
    ON public.items FOR ALL
    USING (true)
    WITH CHECK (true);
