-- ============================================================================
-- Supabase Schema for Starter App (SaaS Task & Project Manager)
-- Run this script in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================================

-- 1. Reset and create items table with full SaaS capabilities
CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    priority TEXT NOT NULL DEFAULT 'medium',
    category TEXT NOT NULL DEFAULT 'Work',
    due_date TIMESTAMPTZ,
    done BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- In case table already exists without the new columns:
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'Work';
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS due_date TIMESTAMPTZ;

-- 2. Performance Indexes
CREATE INDEX IF NOT EXISTS items_user_id_idx ON public.items(user_id);
CREATE INDEX IF NOT EXISTS items_category_idx ON public.items(category);
CREATE INDEX IF NOT EXISTS items_priority_idx ON public.items(priority);

-- 3. Enable Row-Level Security (RLS)
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policy
DROP POLICY IF EXISTS "Allow all for authenticated/service" ON public.items;
CREATE POLICY "Allow all for authenticated/service"
    ON public.items FOR ALL
    USING (true)
    WITH CHECK (true);
